package model.vo;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 11 19:38:08 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApprisalHisLine_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ApprisalHisLine_VOImpl() {
    }

    /**
     * Returns the variable value for b_HistLineId.
     * @return variable value for b_HistLineId
     */
    public BigDecimal getpHistLineId() {
        return (BigDecimal) ensureVariableManager().getVariableValue("pHistLineId");
    }

    /**
     * Sets <code>value</code> for variable b_HistLineId.
     * @param value value to bind as b_HistLineId
     */
    public void setpHistLineId(BigDecimal value) {
        ensureVariableManager().setVariableValue("pHistLineId", value);
    }


    /**
     * Returns the variable value for B_EMPLOYEE_NUMBER.
     * @return variable value for B_EMPLOYEE_NUMBER
     */
    public BigDecimal getB_EMPLOYEE_NUMBER() {
        return (BigDecimal) ensureVariableManager().getVariableValue("B_EMPLOYEE_NUMBER");
    }

    /**
     * Sets <code>value</code> for variable B_EMPLOYEE_NUMBER.
     * @param value value to bind as B_EMPLOYEE_NUMBER
     */
    public void setB_EMPLOYEE_NUMBER(BigDecimal value) {
        ensureVariableManager().setVariableValue("B_EMPLOYEE_NUMBER", value);
    }

    /**
     * Returns the variable value for b_PLAN_NAME.
     * @return variable value for b_PLAN_NAME
     */
    public String getb_PLAN_NAME() {
        return (String) ensureVariableManager().getVariableValue("b_PLAN_NAME");
    }

    /**
     * Sets <code>value</code> for variable b_PLAN_NAME.
     * @param value value to bind as b_PLAN_NAME
     */
    public void setb_PLAN_NAME(String value) {
        ensureVariableManager().setVariableValue("b_PLAN_NAME", value);
    }


}

